version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "22572:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "22570:8000"
    env_file:
      - .env
    environment:
      - FIRST_SUPERUSER_USERNAME=${FIRST_SUPERUSER_USERNAME}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - FIRST_SUPERUSER_EMAIL=${FIRST_SUPERUSER_EMAIL}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "22571:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 